# Mobile App Build Script - Build All Platforms
# Usage: ./build-all.ps1 -ApiUrl "https://your-api.onrender.com"

param(
    [string]$ApiUrl = "https://your-render-backend.onrender.com",
    [string]$Env = "production"
)

$ErrorActionPreference = "Stop"

Write-Host "
╔════════════════════════════════════════════════════════════════╗
║         🚀 YUMMY APP - BUILD ALL PLATFORMS                    ║
║              Android APK + iOS IPA                            ║
╚════════════════════════════════════════════════════════════════╝
" -ForegroundColor Cyan

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$MobileDir = $ScriptDir

# Step 1: Update .env file
Write-Host "`n📝 Configuring environment..." -ForegroundColor Yellow
$EnvFile = Join-Path $MobileDir ".env"

$EnvContent = @"
# Mobile App Configuration
# Auto-generated by build script

EXPO_PUBLIC_ENV=$Env
EXPO_PUBLIC_API_URL=$ApiUrl
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
Write-Host "  ✓ Updated .env file" -ForegroundColor Green
Write-Host "    API URL: $ApiUrl" -ForegroundColor Cyan

# Step 2: Install dependencies
Write-Host "`n📦 Installing dependencies..." -ForegroundColor Yellow
Push-Location $MobileDir
try {
    if (-not (Test-Path "node_modules")) {
        npm install
        Write-Host "  ✓ Dependencies installed" -ForegroundColor Green
    } else {
        Write-Host "  ✓ Dependencies already installed" -ForegroundColor Green
    }
} catch {
    Write-Host "  ✗ Failed to install dependencies" -ForegroundColor Red
    exit 1
} finally {
    Pop-Location
}

# Step 3: Display options
Write-Host "`n📋 Available Platforms:" -ForegroundColor Yellow
Write-Host "  [1] Android APK only" -ForegroundColor Cyan
Write-Host "  [2] iOS IPA only" -ForegroundColor Cyan
Write-Host "  [3] Both (Android + iOS)" -ForegroundColor Cyan
Write-Host "`n❓ Choose option (1-3): " -ForegroundColor Yellow -NoNewline
$Choice = Read-Host

# Step 4: Build based on choice
Push-Location $MobileDir
try {
    switch ($Choice) {
        "1" {
            Write-Host "`n🔨 Building Android APK..." -ForegroundColor Cyan
            eas build --platform android --non-interactive
            Write-Host "`n✅ Android build completed!" -ForegroundColor Green
        }
        "2" {
            Write-Host "`n🔨 Building iOS IPA..." -ForegroundColor Cyan
            eas build --platform ios --non-interactive
            Write-Host "`n✅ iOS build completed!" -ForegroundColor Green
        }
        "3" {
            Write-Host "`n🔨 Building both Android APK and iOS IPA..." -ForegroundColor Cyan
            Write-Host "  Note: Builds will run in parallel" -ForegroundColor Yellow
            eas build --platform all --non-interactive
            Write-Host "`n✅ All builds completed!" -ForegroundColor Green
        }
        default {
            Write-Host "Invalid option" -ForegroundColor Red
            exit 1
        }
    }

    Write-Host "`n📥 Next steps:" -ForegroundColor Yellow
    Write-Host "  1. Visit: https://expo.dev/builds" -ForegroundColor Cyan
    Write-Host "  2. Download your APK and/or IPA" -ForegroundColor Cyan
    Write-Host "  3. Install on your device" -ForegroundColor Cyan

} catch {
    Write-Host "`n✗ Build failed!" -ForegroundColor Red
    Write-Host "Error: $_" -ForegroundColor Red
    exit 1
} finally {
    Pop-Location
}

Write-Host "`n════════════════════════════════════════════════════════════════`n" -ForegroundColor Green
