# Mobile App Build Script for Windows PowerShell
# Usage: ./build-android.ps1 -ApiUrl "https://your-api.onrender.com" -Env production

param(
    [string]$ApiUrl = "https://your-render-backend.onrender.com",
    [string]$Env = "production",
    [switch]$Cloud = $false  # Use cloud build (default) or local
)

$ErrorActionPreference = "Stop"

Write-Host "
╔════════════════════════════════════════════════════════════════╗
║         🚀 YUMMY APP - MOBILE BUILD SCRIPT                    ║
║              Android APK Builder                              ║
╚════════════════════════════════════════════════════════════════╝
" -ForegroundColor Cyan

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$MobileDir = $ScriptDir

# Step 1: Verify Prerequisites
Write-Host "📋 Verifying prerequisites..." -ForegroundColor Yellow

# Check Node.js
try {
    $NodeVersion = node --version
    Write-Host "  ✓ Node.js $NodeVersion" -ForegroundColor Green
} catch {
    Write-Host "  ✗ Node.js not installed" -ForegroundColor Red
    exit 1
}

# Check npm
try {
    $NpmVersion = npm --version
    Write-Host "  ✓ npm $NpmVersion" -ForegroundColor Green
} catch {
    Write-Host "  ✗ npm not installed" -ForegroundColor Red
    exit 1
}

# Check Expo CLI
try {
    $ExpoVersion = expo --version
    Write-Host "  ✓ Expo CLI $ExpoVersion" -ForegroundColor Green
} catch {
    Write-Host "  ⚠ Expo CLI not installed" -ForegroundColor Yellow
    Write-Host "  Installing Expo CLI globally..." -ForegroundColor Yellow
    npm install -g expo-cli
}

# Check EAS CLI
try {
    $EasVersion = eas --version
    Write-Host "  ✓ EAS CLI $EasVersion" -ForegroundColor Green
} catch {
    Write-Host "  ⚠ EAS CLI not installed" -ForegroundColor Yellow
    Write-Host "  Installing EAS CLI globally..." -ForegroundColor Yellow
    npm install -g eas-cli
}

# Step 2: Update .env file
Write-Host "`n📝 Configuring environment..." -ForegroundColor Yellow
$EnvFile = Join-Path $MobileDir ".env"

$EnvContent = @"
# Mobile App Configuration
# Auto-generated by build script

EXPO_PUBLIC_ENV=$Env
EXPO_PUBLIC_API_URL=$ApiUrl
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
Write-Host "  ✓ Updated .env file" -ForegroundColor Green
Write-Host "    Environment: $Env" -ForegroundColor Cyan
Write-Host "    API URL: $ApiUrl" -ForegroundColor Cyan

# Step 3: Install dependencies
Write-Host "`n📦 Installing dependencies..." -ForegroundColor Yellow
Push-Location $MobileDir
try {
    # Check if node_modules exists
    if (-not (Test-Path "node_modules")) {
        npm install
        Write-Host "  ✓ Dependencies installed" -ForegroundColor Green
    } else {
        Write-Host "  ✓ Dependencies already installed" -ForegroundColor Green
    }
} catch {
    Write-Host "  ✗ Failed to install dependencies" -ForegroundColor Red
    Write-Host "  Error: $_" -ForegroundColor Red
    exit 1
} finally {
    Pop-Location
}

# Step 4: Check EAS Configuration
Write-Host "`n⚙️  Checking EAS configuration..." -ForegroundColor Yellow
$EasJsonFile = Join-Path $MobileDir "eas.json"

if (-not (Test-Path $EasJsonFile)) {
    Write-Host "  ⚠ eas.json not found" -ForegroundColor Yellow
    Write-Host "  Run 'eas build:configure' first" -ForegroundColor Cyan
    Write-Host "  Or copy template from build script directory" -ForegroundColor Cyan
    exit 1
} else {
    Write-Host "  ✓ eas.json configured" -ForegroundColor Green
}

# Step 5: Display build options
Write-Host "`n🔨 Build Options:" -ForegroundColor Yellow
Write-Host "  Platform: Android" -ForegroundColor Cyan
Write-Host "  Type: APK" -ForegroundColor Cyan
Write-Host "  Build Mode: $(if ($Cloud) { 'Cloud (EAS)' } else { 'Cloud (EAS) - Recommended' })" -ForegroundColor Cyan

# Step 6: Confirm before building
Write-Host "`n❓ Proceed with build? (y/n): " -ForegroundColor Yellow -NoNewline
$Confirm = Read-Host

if ($Confirm -ne "y" -and $Confirm -ne "Y") {
    Write-Host "Build cancelled." -ForegroundColor Red
    exit 0
}

# Step 7: Build APK
Write-Host "`n🚀 Starting build..." -ForegroundColor Cyan

Push-Location $MobileDir
try {
    # Build using EAS (cloud)
    Write-Host "
Building with EAS Cloud Build...
  • This will upload to Expo servers
  • No need for Android Studio
  • Faster parallel builds
  • Free tier available

Waiting for build to start..." -ForegroundColor Cyan

    eas build --platform android --non-interactive

    Write-Host "`n✅ Build completed successfully!" -ForegroundColor Green
    Write-Host "`n📥 Next steps:" -ForegroundColor Yellow
    Write-Host "  1. Check your email for download link" -ForegroundColor Cyan
    Write-Host "  2. Or visit: https://expo.dev/builds" -ForegroundColor Cyan
    Write-Host "  3. Download the .apk file" -ForegroundColor Cyan
    Write-Host "  4. Transfer to Android phone" -ForegroundColor Cyan
    Write-Host "  5. Tap to install" -ForegroundColor Cyan

} catch {
    Write-Host "`n✗ Build failed!" -ForegroundColor Red
    Write-Host "Error: $_" -ForegroundColor Red
    exit 1
} finally {
    Pop-Location
}

Write-Host "`n" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Green
