# Mobile App Build Script for Windows PowerShell
# Usage: ./build-ios.ps1 -ApiUrl "https://your-api.onrender.com" -Env production

param(
    [string]$ApiUrl = "https://your-render-backend.onrender.com",
    [string]$Env = "production"
)

$ErrorActionPreference = "Stop"

Write-Host "
╔════════════════════════════════════════════════════════════════╗
║         🚀 YUMMY APP - MOBILE BUILD SCRIPT                    ║
║              iOS IPA Builder                                  ║
╚════════════════════════════════════════════════════════════════╝
" -ForegroundColor Cyan

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$MobileDir = $ScriptDir

# Step 1: Verify Prerequisites
Write-Host "📋 Verifying prerequisites..." -ForegroundColor Yellow

# Check Node.js
try {
    $NodeVersion = node --version
    Write-Host "  ✓ Node.js $NodeVersion" -ForegroundColor Green
} catch {
    Write-Host "  ✗ Node.js not installed" -ForegroundColor Red
    exit 1
}

# Check EAS CLI
try {
    $EasVersion = eas --version
    Write-Host "  ✓ EAS CLI $EasVersion" -ForegroundColor Green
} catch {
    Write-Host "  ✗ EAS CLI not installed" -ForegroundColor Red
    Write-Host "  Installing EAS CLI globally..." -ForegroundColor Yellow
    npm install -g eas-cli
}

Write-Host "`n📌 NOTE: iOS builds require:" -ForegroundColor Yellow
Write-Host "  • Apple Developer Account ($99/year)" -ForegroundColor Cyan
Write-Host "  • EAS will handle signing (recommended)" -ForegroundColor Cyan
Write-Host "  • First-time setup may take 10+ minutes" -ForegroundColor Cyan

# Step 2: Update .env file
Write-Host "`n📝 Configuring environment..." -ForegroundColor Yellow
$EnvFile = Join-Path $MobileDir ".env"

$EnvContent = @"
# Mobile App Configuration
# Auto-generated by build script

EXPO_PUBLIC_ENV=$Env
EXPO_PUBLIC_API_URL=$ApiUrl
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
Write-Host "  ✓ Updated .env file" -ForegroundColor Green
Write-Host "    Environment: $Env" -ForegroundColor Cyan
Write-Host "    API URL: $ApiUrl" -ForegroundColor Cyan

# Step 3: Install dependencies
Write-Host "`n📦 Installing dependencies..." -ForegroundColor Yellow
Push-Location $MobileDir
try {
    if (-not (Test-Path "node_modules")) {
        npm install
        Write-Host "  ✓ Dependencies installed" -ForegroundColor Green
    } else {
        Write-Host "  ✓ Dependencies already installed" -ForegroundColor Green
    }
} catch {
    Write-Host "  ✗ Failed to install dependencies" -ForegroundColor Red
    exit 1
} finally {
    Pop-Location
}

# Step 4: Check EAS Configuration
Write-Host "`n⚙️  Checking EAS configuration..." -ForegroundColor Yellow
$EasJsonFile = Join-Path $MobileDir "eas.json"

if (-not (Test-Path $EasJsonFile)) {
    Write-Host "  ⚠ eas.json not found" -ForegroundColor Yellow
    Write-Host "  Run 'eas build:configure' first" -ForegroundColor Cyan
    exit 1
} else {
    Write-Host "  ✓ eas.json configured" -ForegroundColor Green
}

# Step 5: Display build options
Write-Host "`n🔨 Build Options:" -ForegroundColor Yellow
Write-Host "  Platform: iOS" -ForegroundColor Cyan
Write-Host "  Type: IPA (Archive)" -ForegroundColor Cyan
Write-Host "  Build Mode: Cloud (EAS)" -ForegroundColor Cyan

# Step 6: Confirm before building
Write-Host "`n❓ Proceed with build? (y/n): " -ForegroundColor Yellow -NoNewline
$Confirm = Read-Host

if ($Confirm -ne "y" -and $Confirm -ne "Y") {
    Write-Host "Build cancelled." -ForegroundColor Red
    exit 0
}

# Step 7: Build IPA
Write-Host "`n🚀 Starting iOS build..." -ForegroundColor Cyan

Push-Location $MobileDir
try {
    Write-Host "
Building with EAS Cloud Build...
  • This will build on Apple servers
  • Requires Apple Developer credentials
  • EAS will prompt for signing details
  • Build time: 15-20 minutes

Waiting for build to start..." -ForegroundColor Cyan

    eas build --platform ios --non-interactive

    Write-Host "`n✅ iOS build completed!" -ForegroundColor Green
    Write-Host "`n📥 Next steps:" -ForegroundColor Yellow
    Write-Host "  1. Visit: https://expo.dev/builds" -ForegroundColor Cyan
    Write-Host "  2. Find your iOS build" -ForegroundColor Cyan
    Write-Host "  3. Download or use TestFlight" -ForegroundColor Cyan
    Write-Host "  4. Install on iPhone" -ForegroundColor Cyan

} catch {
    Write-Host "`n✗ Build failed!" -ForegroundColor Red
    Write-Host "Error: $_" -ForegroundColor Red
    Write-Host "`nTroubleshooting:" -ForegroundColor Yellow
    Write-Host "  • Ensure Apple Developer Account is setup" -ForegroundColor Cyan
    Write-Host "  • Check EAS credentials: eas build:configure" -ForegroundColor Cyan
    exit 1
} finally {
    Pop-Location
}

Write-Host "`n" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Green
