export const ORDER_STATUS = {
  PENDING: "pending",
  PAYMENT_PROCESSING: "payment_processing",
  PAYMENT_FAILED: "payment_failed",
  PAID: "paid",
  CONFIRMED: "confirmed",
  REJECTED: "rejected",
  PREPARING: "preparing",
  READY: "ready",
  DRONE_ASSIGNED: "drone_assigned",
  PICKING_UP: "picking_up",
  PICKED_UP: "picked_up",
  DELIVERING: "delivering",
  DELIVERED: "delivered",
  CANCELLED: "cancelled",
  REFUNDING: "refunding",
  REFUNDED: "refunded",
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: "Pending Payment",
  [ORDER_STATUS.PAYMENT_PROCESSING]: "Processing Payment",
  [ORDER_STATUS.PAYMENT_FAILED]: "Payment Failed",
  [ORDER_STATUS.PAID]: "Paid",
  [ORDER_STATUS.CONFIRMED]: "Confirmed",
  [ORDER_STATUS.REJECTED]: "Rejected",
  [ORDER_STATUS.PREPARING]: "Preparing",
  [ORDER_STATUS.READY]: "Ready",
  [ORDER_STATUS.DRONE_ASSIGNED]: "Drone Assigned",
  [ORDER_STATUS.PICKING_UP]: "Picking Up",
  [ORDER_STATUS.PICKED_UP]: "Picked Up",
  [ORDER_STATUS.DELIVERING]: "Delivering",
  [ORDER_STATUS.DELIVERED]: "Delivered",
  [ORDER_STATUS.CANCELLED]: "Cancelled",
  [ORDER_STATUS.REFUNDING]: "Refunding",
  [ORDER_STATUS.REFUNDED]: "Refunded",
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: "gray",
  [ORDER_STATUS.PAYMENT_PROCESSING]: "blue",
  [ORDER_STATUS.PAYMENT_FAILED]: "red",
  [ORDER_STATUS.PAID]: "green",
  [ORDER_STATUS.CONFIRMED]: "green",
  [ORDER_STATUS.REJECTED]: "red",
  [ORDER_STATUS.PREPARING]: "yellow",
  [ORDER_STATUS.READY]: "green",
  [ORDER_STATUS.DRONE_ASSIGNED]: "blue",
  [ORDER_STATUS.PICKING_UP]: "blue",
  [ORDER_STATUS.PICKED_UP]: "blue",
  [ORDER_STATUS.DELIVERING]: "blue",
  [ORDER_STATUS.DELIVERED]: "green",
  [ORDER_STATUS.CANCELLED]: "red",
  [ORDER_STATUS.REFUNDING]: "yellow",
  [ORDER_STATUS.REFUNDED]: "green",
};
