export const ORDER_STATUS = {
  PENDING: "pending",
  PAYMENT_PROCESSING: "payment_processing",
  PAYMENT_FAILED: "payment_failed",
  PAID: "paid",
  CONFIRMED: "confirmed",
  REJECTED: "rejected",
  PREPARING: "preparing",
  READY: "ready",
  DRONE_ASSIGNED: "drone_assigned",
  PICKING_UP: "picking_up",
  PICKED_UP: "picked_up",
  DELIVERING: "delivering",
  DELIVERED: "delivered",
  CANCELLED: "cancelled",
  REFUNDING: "refunding",
  REFUNDED: "refunded",
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: "Chờ thanh toán",
  [ORDER_STATUS.PAYMENT_PROCESSING]: "Đang thanh toán",
  [ORDER_STATUS.PAYMENT_FAILED]: "Thanh toán thất bại",
  [ORDER_STATUS.PAID]: "Đã thanh toán",
  [ORDER_STATUS.CONFIRMED]: "Đã xác nhận",
  [ORDER_STATUS.REJECTED]: "Đã từ chối",
  [ORDER_STATUS.PREPARING]: "Đang chuẩn bị",
  [ORDER_STATUS.READY]: "Sẵn sàng",
  [ORDER_STATUS.DRONE_ASSIGNED]: "Đã gán drone",
  [ORDER_STATUS.PICKING_UP]: "Đang lấy món",
  [ORDER_STATUS.PICKED_UP]: "Đã lấy món",
  [ORDER_STATUS.DELIVERING]: "Đang giao",
  [ORDER_STATUS.DELIVERED]: "Đã giao",
  [ORDER_STATUS.CANCELLED]: "Đã hủy",
  [ORDER_STATUS.REFUNDING]: "Đang hoàn tiền",
  [ORDER_STATUS.REFUNDED]: "Đã hoàn tiền",
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: "gray",
  [ORDER_STATUS.PAYMENT_PROCESSING]: "blue",
  [ORDER_STATUS.PAYMENT_FAILED]: "red",
  [ORDER_STATUS.PAID]: "green",
  [ORDER_STATUS.CONFIRMED]: "green",
  [ORDER_STATUS.REJECTED]: "red",
  [ORDER_STATUS.PREPARING]: "yellow",
  [ORDER_STATUS.READY]: "green",
  [ORDER_STATUS.DRONE_ASSIGNED]: "blue",
  [ORDER_STATUS.PICKING_UP]: "blue",
  [ORDER_STATUS.PICKED_UP]: "blue",
  [ORDER_STATUS.DELIVERING]: "blue",
  [ORDER_STATUS.DELIVERED]: "green",
  [ORDER_STATUS.CANCELLED]: "red",
  [ORDER_STATUS.REFUNDING]: "yellow",
  [ORDER_STATUS.REFUNDED]: "green",
};
